version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub
      - echo "$password" | docker login -u "$username" --password-stdin

  build:
    commands:
      - echo Building backend image
      - docker build -t akanksha2501/devbank-backend:v5 ./backend

      - echo Building frontend image
      - docker build -t akanksha2501/devbank-frontend:v5 ./frontend

  post_build:
    commands:
      - echo Pushing backend image
      - docker push akanksha2501/devbank-backend:v5

      - echo Pushing frontend image
      - docker push akanksha2501/devbank-frontend:v5

      - echo Build completed
